- README.md
- group_vars/_skel/cluster_vars.yml
- jenkinsfiles/Jenkinsfile_exec_deploy
- jenkinsfiles/Jenkinsfile_exec_release
- jenkinsfiles/Jenkinsfile_exec_release_deploy
- roles/clusterverse/clean/tasks/gce.yml
- roles/clusterverse/cluster_hosts/tasks/aws.yml
- roles/clusterverse/cluster_hosts/tasks/gce.yml
- roles/clusterverse/cluster_hosts/tasks/main.yml
- roles/clusterverse/create/tasks/gce.yml
- roles/clusterverse/redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/gce_del.yml
- roles/clusterverse/redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/gce_rescue_instance.yml
- roles/clusterverse/redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/gce_stop_instance.yml
- roles/clusterverse/redeploy/_scheme_rmvm_rmdisks_only/tasks/gce_del.yml
+ Define the clusters as a count of nodes per AZ, rather than a count of AZ-clusters.  Allows us to have non-multiples of availability zones (e.g. 5 Zookeeper nodes).
+ Fix GCP redeploy: gcp_compute_instance changed in 2.9.  deletion_protection is now defined in gcp_compute_instance, and must be set.  Labels also must always be set, or their absence causes them to be removed.
> Increase cluster definition flexibility.  Fix GCP redeploy in Ansible 2.9

- clean/tasks/main.yml
Made use of cluster_vars.route53_private_zone in the clean role in the same way it's used in the config role
> Fix Route53 deletion with private zones

- create/tasks/aws.yml
- create/tasks/gce.yml
This PR fixes two items:
1. Line 49 - The `gcp_compute_subnetwork_info` module has a mandatory parameter `region` and this was not set in the code, so setting the var `gcp_compute_subnetwork_info` currently fails. Further info [here](https://docs.ansible.com/ansible/latest/modules/gcp_compute_subnetwork_info_module.html#gcp-compute-subnetwork-info-module).
2. Line 100 - GCP labels only support lowercase characters. My username by default in AD is all uppercase so when creating labels in ansible from my local machine, the build results in a failure. Further info [here](https://cloud.google.com/compute/docs/labeling-resources#label_format).
> [FIX] Add region args as required and convert owner label to lowercase

- EXAMPLE/README.md
While testing PR #26, I invoked the `redeploy.yml` playbook, however the script failed due to the following assertion:
```
TASK [clusterverse/redeploy : assert] ***********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
"assertion": "canary is defined and (canary is defined and canary in ['start', 'finish', 'none'])",
"changed": false,
"evaluated_to": false,
"msg": "Canary must be 'start', 'finish' or 'none'"
}
PLAY RECAP **************************************************************************************************************************************************************************************** …
```
> [DOCS] Canary variable mandatory for redeploy invocation

- EXAMPLE/jenkinsfiles/Jenkinsfile_exec_release
.. to avoid job failure if no downstream release-deploy exists.
> [FIX] Commented out additional deploy step after GH release creation

- EXAMPLE/group_vars/test_gce_euw1/cluster_vars.yml
- clean/tasks/gce.yml
- config/tasks/main.yml
- dynamic_inventory/tasks/main.yml
This PR implements the following:
* Retrieves a managed zone in GCP using the value stored in var `dns_tld_external` under `cluster_vars.yml`
* Adds a A record under the managed zone provided 
* Adds a CNAME record under the managed zone provided
* If the GCP managed zone is `private`, the value of the A record will be the private ip of the VM
* If the GCP managed zone is `public`, the value of the A record will be the public ip of the VM
The following pre-requisites are required for the code to work:
* Pre-existing managed zone within GCP
* Setting the var `dns_tld_external` to the `dns name` of the GCP managed zone and including the `.` i.e. `clusterverse.vtp.com.`
* Setting the var `dns_server` to `clouddns` under `cluster_vars.yml`
> [FEATURE] Add Cloud DNS automation for GCP A/CNAME records

- EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
- config/tasks/cloud_agents.yml
- config/tasks/disks_auto.yml
- config/tasks/disks_auto_aws_nvme.yml
- config/tasks/filebeat.yml
- Add CentOS support by configuring a distro agnostic approach to disk configuration
- Modify Filebeat, Qualy and Nessus agent installs to work with `yum`
This has been tested on `aws` and `gcp` across `ubuntu` and `centos` on both
> [FEATURE] Centos support init

- clean/tasks/gce.yml
- config/tasks/main.yml
- dynamic_inventory/tasks/main.yml
The previous module (`wait_for`) probed port 22 on the remote hosts directly from the machine running ansible, using a tcp connection.
This meant that the module wasn't using SSH and therefore overriding any `ssh_args` in the ansible.cfg file, as well as potential jump-hosts.
The fix introduces a harmless module, `ping`, while delegating the action to the destination host - thus forcing SSH connectivity to the host (and therefore testing that sshd is up and running), while introducing `retries` to the module in case the host is immediately unavailable.
> [FIX] Switch from wait_for to ping + delegate_to to force SSH usage

- _dependencies/action_plugins/README_merge_vars.md
- _dependencies/action_plugins/merge_vars.py
- _dependencies/defaults/main.yml
- _dependencies/tasks/main.yml
Add support for another approach to load group_vars from external repository and not from group_vars.
As an example:
we have external repository that contains cluster and application configuration based on Cloud/Region/App/Etc
```
environment/
└── aws
├── cbe
│   └── tan02
│       ├── app_vars.yml
│       ├── cluster.yml
│       └── dev_metadata.yml
└── dev.yml
```
How to use:
In group_vars you need `all.yml` that contains list of configuration files(order matters)
```
merge_dict_vars_list:
- "./environment/{{ _cloud_type }}/{{ buildenv }}.yml"
- "./environment/{{ _cloud_type }}/{{ app_name }}/{{ clusterid }}/cluster.yml"
- "./environment/{{ _cloud_type }}/{{ app_name }}/{{ clusterid }}/{{ buildenv }}_metadata.yml"
- "./environment/{{ _cloud_type }}/{{ app_name }}/{{ clusterid …
```
> Add support for another approach to load group_vars

- cluster_hosts/tasks/get_cluster_hosts_target.yml
Incorrect argument 'shapshot_id' used for 'ec2' module, modified to 'snapshot'
> [FIX] can you spot 'h' in 'shapshot_id'? modified to 'snapshot'

- EXAMPLE/ansible.cfg
Set Python interpreter discovery in ansible.cfg, under the [default] section: `interpreter_python: auto`.
This covers edge-cases where Ansible doesn't discover Python's path in a target host.
Will be a default setting starting in 2.12, as explained here: https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html
> [FEATURE] Set Python interpreter discovery in ansible.cfg

- cluster_hosts/tasks/get_cluster_hosts_target.yml
Fix on asserting multiple tags while filtering snapshots and ensuring number of hosts is same as number of snapshots found.
> Assert: multiple tags filtering snapshots

- EXAMPLE/README.md
- EXAMPLE/group_vars/_skel/cluster_vars.yml
- EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/app_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/cluster_vars.yml
- clean/tasks/clean_dns.yml
- clean/tasks/main.yml
- config/tasks/create_dns_a.yml
- config/tasks/main.yml
- readiness/tasks/config_dns_cname.yml
- readiness/tasks/main.yml
- redeploy/_scheme_addallnew_rmdisk_rollback/tasks/main.yml
- redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/main.yml
The naming of the variables that describe the DNS zone to which we're adding records (`dns_tld_external`), the name of the domain part of the FQDN (`cluster_vars.dns_zone_external`), and the name of the domain part of the cloud-internal FQDN (`cluster_vars.dns_zone_internal`) is very poor, and leads to misunderstandings.
```
dns_tld_external  --> cluster_vars.dns_nameserver_zone
dns_zone_internal --> cluster_vars.dns_cloud_internal_domain
dns_zone_external --> cluster_vars.dns_fqdn_domain
```
> Rename poorly-named DNS variables

- EXAMPLE/.vaultpass-client.py
- EXAMPLE/Pipfile
- EXAMPLE/cluster.yml
- EXAMPLE/clusterverse_label_upgrade_v1-v2.yml
- EXAMPLE/group_vars/_skel/cluster_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/cluster_vars.yml
- EXAMPLE/jenkinsfiles/Jenkinsfile_exec_release
- clean/tasks/clean_dns.yml
- clean/tasks/clean_networking.yml
- clean/tasks/clean_vms.yml
- cluster_hosts/tasks/get_cluster_hosts_state.yml
- config/tasks/create_dns_a.yml
- create/tasks/gcp.yml
- dynamic_inventory/tasks/gcp.yml
- readiness/tasks/config_dns_cname.yml
- readiness/tasks/remove_maintenance_mode.yml
- redeploy/__common/tasks/poweroff_vms.yml
- redeploy/__common/tasks/poweron_vms.yml
- redeploy/__common/tasks/set_lifecycle_state_label.yml
When GCP is configured with 'Shared VPCs' (https://cloud.google.com/vpc/docs/shared-vpc), the network resources are no longer in the same VPC as the compute resources.  
This change splits out the 'vpc_project_id' (the 'service project', with the VMs in it), from the 'vpc_host_project_id' (the 'service project', where the networking is located).
> Support separate GCP 'host' and 'service' projects

- clean/tasks/clean_dns.yml
Support cleaning (creating already supported) of multiple DNS managed zones per DNS name (i.e. same name for both private and public zones).
> Support cleaning of multiple DNS managed zones per DNS name (GCP)

- EXAMPLE/group_vars/_skel/cluster_vars.yml
- EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/cluster_vars.yml
- config/tasks/filebeat.yml
- config/tasks/metricbeat.yml
- config/templates/etc/filebeat/filebeat.yml.j2
- config/templates/etc/metricbeat/metricbeat.yml.j2
As suggested by @dseeley, reworked on the structure for the `beats` configuration:
```
beats_config:
filebeat:
output_logstash_hosts: ["localhost:5044"]   # The destination hosts for filebeat-gathered logs
extra_logs_paths: # The array is optional, if you need to add more paths or files to scrape for logs
- /var/log/myapp/*.log 
metricbeat:
output_logstash_hosts: ["localhost:5044"]   # The destination hosts for metricbeat-gathered metrics
```
NB:
- `beats_target_hosts` is still usable together with the new var `beats_config.filebeat.output_logstash_hosts` to avoid breaking backwards compatibility (the playbook checks for both variables)
- `beats_config.filebeat.elasticsearch_output_hosts` has been added to the configuration, but is not recognised by the playbook nor documented yet. …
> [FEATURE] Improved beats configuration structure

- EXAMPLE/README.md
- EXAMPLE/ansible.cfg
- EXAMPLE/cluster.yml
- EXAMPLE/group_vars/_skel/cluster_vars.yml
- EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/cluster_vars.yml
- _dependencies/defaults/main.yml
- dynamic_inventory/tasks/main.yml
+ Jinja2 in Ansible is set to always delete whitespace before and after the expression, so the lines of inventory are concatenated. Fix the logic, by adding a "{{''}}" to the end of the jinja2 expression.
+ Simplify the EXAMPLE/cluster.yml to remove the anchors and aliases (& and *), which add no value here as they have to be duplicated instead of the tags they're referencing.
> Fix the logic that writes the dynamic inventory to file

- EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/cluster_vars.yml
- config/tasks/metricbeat.yml
- config/templates/etc/metricbeat/metricbeat_system.yml.j2
This PR enables Metricbeat to ship disks related metrics such as incoming/outgoing read/writes per second and iowait.
- Enables Metricbeat diskio system module
- Provides default configuration template for mb system module
- Diskio looks for all partitions by default when undefined; when defined as below in `cluster_vars.yml`, looks for the desired partitions only:
```bash
metricbeat:
output_logstash_hosts: ["localhost:5044"]  
diskio:
include_devices: ["sda", "sdb", "nvme0n1", "nvme1n1", "nvme2n1"]
```
> [FEATURE] Enable Metricbeat diskio module

- EXAMPLE/group_vars/_skel/cluster_vars.yml
- EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
- EXAMPLE/group_vars/test_gcp_euw1/cluster_vars.yml
- config/tasks/cloud_agents.yml
Moved from downloading qualys agent from S3 bucket to security github repo.
I have tested this with Jenkins build with Giuseppe and Antoine
> [FIX] Replaced qualys agents to be pulled from github repo

- redeploy/_scheme_addallnew_rmdisk_rollback/tasks/main.yml
- redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/main.yml
- redeploy/_scheme_rmvm_keepdisk_rollback/tasks/main.yml
Because playbook failure can occur in include_tasks, variables that are used in those tasks have to be resolved, which doesn't happen after the failure has occurred (and the variables they depended on have changed) so we need to default the variables.
> Fix the misleading rollback error messages, when failure occurs in include_tasks.

- create/tasks/aws.yml
In newer Ansible versions (i.e. 2.10.6) the ec2_vol module does not accept an empty volume_size var if attaching an existing volume. Volume_size param should not exist in this case. This issue has been observed while redeploying (scheme _scheme_rmvm_keepdisk_rollback):
TASK [create/aws | Attach (or create) volumes where 'src' is present (e.g. inserted as part of _scheme_rmvm_keepdisk_rollback scheme)]
fatal: [localhost]: FAILED! => changed=false
msg: 'argument volume_size is of type <class ''str''> and we were unable to convert to int: <class ''str''> cannot be converted to an int'
The change has been successfully tested in creation (cluster.yml) and redeploy (redeploy.yml) playbooks.
> Fix ec2_vol volume_size parameter

- config/templates/etc/filebeat/filebeat.yml.j2
If defined, `close_timeout` will help preventing filebeat from retaining logs files which might cause the disk to be filled up
> [FEATURE] Add close_timeout to filebeat config

- EXAMPLE/jenkinsfiles/Jenkinsfile_ops
- _dependencies/tasks/main.yml
- clean/tasks/dns.yml
- config/tasks/main.yml
- jenkinsfiles/Jenkinsfile_testsuite
cherry-picked from https://github.com/dseeley/clusterverse/commit/de0939ef45c3817a7918d4a694626ce230f4c64f
+ Removes restriction on Ansible <= 2.10.6.  Can now be either 2.9.6...2.10.6 or >4.0.0 (core 2.11.0).
+ The method of getting `route53` records (using `route53` module with `state=get`), has an issue in 2.10.7 <= Ansible < 4 where the return values have changed due to boto3 migration (https://github.com/ansible-collections/community.aws/issues/523).  This is fixed in `community.aws` v1.5.0 (Ansible 4.0).
+ Also apply a fix to the `state=get`  mechanism to not fail when the records are not found.
+ The `state=get` function on the route53 module is not likely to remain supported indefinitely, so this optionally supports using `route53_info` instead (needs `-e use_new_route53=true`).
+ …
> Enable Ansible 4. Optionally use route53_info to get record sets for delete

- EXAMPLE/README.md
- README.md
- redeploy/_scheme_addallnew_rmdisk_rollback/tasks/main.yml
- redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/redeploy_by_hosttype.yml
- redeploy/_scheme_rmvm_keepdisk_rollback/tasks/by_hosttype.yml
- redeploy/_scheme_rmvm_keepdisk_rollback/tasks/main.yml
- redeploy/_scheme_rmvm_keepdisk_rollback/tasks/preflight.yml
- redeploy/_scheme_rmvm_rmdisk_only/tasks/by_hosttype.yml
- redeploy/tasks/main.yml
- Added support for a new canary option called filter for the _scheme_addnewvm_rmdisk_rollback, _scheme_rmvm_rmdisk_only and _scheme_rmvm_keepdisk_rollback redeploy schemes
- Documented the filter canary option in the README
- Added appropriate checks
> Filter canary option

- config/handlers/main.yml
Fixes an edge-case where recent versions of Ansible do not enable / start metricbeat when `service.enabled` is set to `true` instead of `yes`.
> [FIX] Fixed metricbeat service restart step

- config/templates/etc/filebeat/filebeat.yml.j2
- Enables external inputs in Filebeat for configuring multiple application specific logs.
- Fixes extra_logs_paths as optional variable.
> Filebeat support for external inputs

- config/tasks/create_dns_a.yml
Following the discussion on https://github.com/sky-uk/clusterverse/pull/111 I'm submitting this PR. This change handles the `Timeout waiting for resource records changes to be applied: Waiter ResourceRecordSetsChanged failed: Rate exceeded` errors introducing a `rescue` task which, in case of failure, resubmits all the records missed at first glance in synchronous fashion.
This has been extensively tested with 30+ nodes clusters:
- tested cluster creation
- tested cluster redeploy
- tested clean
> [FIX] Handle Route53 rate limit error

- config/tasks/cloud_agents.yml
This PR is raised to allow users to be able to download and install the Tenable Nessus Cloud Agent onto their hosted machines. 
This would be a sample payload added in the `cluster_vars` configuration :
````
cloud_agent:
tenable:
service: "nessusagent"
github_release: "https://api.github.com/repos/sky-uk/crs-tenable-agent-ansible/releases"
debpackage: ""
bin_path: "/opt/nessus_agent/sbin"
nessus_key_id: ""
nessus_group_id: ""
````
- Tested via Jenkins 
Output : 
````
ubuntu@jtn05-ccs-dev-es-data-a0-1649261763:~$ systemctl status nessusagent
● nessusagent.service - The Nessus Client Agent
Loaded: loaded (/lib/systemd/system/nessusagent.service; enabled; vendor preset: enabled)
Active: active (running) since Wed 2022-04-06 20:44:07 UTC; 23s ago
Main PID: 21462 (nessus-service)
Tasks: 3 …
```
> [FEATURE] Add Tenable Nessus Download and Installation Process Using Binary File 

- EXAMPLE/cluster_defs/aws/testid/eu-west-1/sandbox/cluster_vars__buildenv.yml
- create/tasks/create_aws.yml
This change gives the ability to have `instance_profile_name` defined depending on the host type. The option to have a generic `instance_profile_name` per cluster is kept.
This was successfully tested in the scenarios below:
- 2 different host types with 1 `instance_profile_name` each
- 3 different host types:  1 host type had 1 `instance_profile_name` and other 2 had generic `instance_profile_name`
Regression tests:
- no `instance_profile_name`
- generic `instance_profile_name`
> [FEATURE] Give the option to define different instance_profile_name per host type

- EXAMPLE/cluster_defs/cluster_vars.yml
- cluster_hosts/tasks/get_cluster_hosts_target.yml
This is raised to deal with the fact that AWS AMIs have 2 years life, after which, AMIs are not available anymore. 
```
TASK [cluster_hosts : get_cluster_hosts_target/aws | Replace image with the latest AMI found at 'manifest-location'] ***
'image': AnsibleUndefined
```
Setting `override_deprecated_ami: true` allows to have clusters with mix of new and deprecated AMIs.
> [FIX] Add ability to ignore deprecated AMI

- EXAMPLE/cluster_defs/aws/cluster_vars__cloud.yml
- create/tasks/create_aws.yml
Some of the regions are not available for aws module boto.ec2. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path
Specifying `ec2_url` into `ec2` invocation fixes the issue
> [FEATURE] Make ec2 module working in all the regions

- _dependencies/defaults/main.yml
- clean/tasks/aws.yml
- cluster_hosts/tasks/get_cluster_hosts_state_aws.yml
- config/handlers/main.yml
- config/tasks/chrony.yml
- config/tasks/create_dns_a.yml
- config/tasks/main.yml
- create/tasks/create_aws.yml
- redeploy/_scheme_rmvm_keepdisk_rollback/tasks/preflight.yml
Move from ec2 to `amazon.aws.ec2_instance` module.
volumes structure changed for `ec2_instance`; maintain old syntax in `cluster_defs`.
Spot instances no longer supported
`Chrony` changes showing although already merged
> [FEATURE] ec2 to ec2_instance 

- create/tasks/create_aws.yml
This fix from upstream should fix the issue we see when building from scratch where builds fail on the security group parameter
> Deal with potentially empty security group config

- config/tasks/cloud_agents.yml
This change helps making sure the latest version of the cloud agent is downloaded and installed
> [FIX] Allow file override for cloud agents install

- config/tasks/cloud_agents.yml
- config/tasks/main.yml
This PR updates the Qualys cloud agent installation process to handle the new GitHub release format, where the agent files are provided in a tarball instead of directly as deb packages. The old code would directly download and install the deb file but the new format is handling zip/tar files. 
It adds steps to download, extract the tarball, install the agent, and clean up temporary files and directories after installation.
Has been tested extensively as by the commit history and is working fine. A small amendment will be needed in dependent repositories to include the  tarball_url being `https://github.com/sky-uk/crs-qualys-agent-ansible/archive/refs/tags`. This code ensures the latest release is retrieved each time.
> [FIX] Qualys installation to include zip file
